export class Usuario {
    constructor(
      public apellido: string,
      public bio:string,
      public canton: string,
      public categoria: string,
      public ciudad: string,
      public departamento:string,
      public direccion: string,
      public email_principal: string,
      public estado_civil: string,
      public facultad:  string,
      public fecha_de_nacimiento: string,
      public foto_web_low:  string,
      public genero:  string,
      public lugar_de_nacimiento: string,
      public modalidad_contractual:string,
      public nacionalidad: string,
      public nombre: string,
      public pais_de_residencia: string,
      public parroquia: string,
      public primer_apellido:string,
      public primer_nombre: string,
      public provincia:  string,
      public related: string,
      public segundo_apellido: string,
      public segundo_nombre:string,
      public status_id: string,
      public telefono_institucion: string,
      public tipo_docente: string,
      public titular_id: string,
      public cedula?: string,
      public id?: number,
      
    ) {
        this.apellido = apellido,
        this.bio = bio,
        this.canton = this.canton,
        this.categoria = this.categoria,
        this.cedula = this.cedula,
        this.ciudad = this.ciudad,
        this.departamento = this.departamento,
        this.direccion = this.direccion,
        this.email_principal = this.email_principal,
        this.estado_civil = this.estado_civil,
        this.facultad  = this.facultad,
        this.fecha_de_nacimiento = this.fecha_de_nacimiento
        this.foto_web_low   = this.foto_web_low,
        this.genero  = this.genero,
        this.lugar_de_nacimiento = this.lugar_de_nacimiento,
        this.modalidad_contractual = this.modalidad_contractual,
        this.nacionalidad  = this.nacionalidad,
        this.nombre = this.nombre,
        this.pais_de_residencia = this.pais_de_residencia,
        this.parroquia = this.parroquia,
        this.primer_apellido = this.primer_apellido
        this.primer_nombre = this.primer_nombre,
        this.provincia = this.provincia,
        this.related  = this.related,
        this.segundo_apellido = this.segundo_apellido,
        this.segundo_nombre = this.segundo_nombre,
        this.status_id = this.status_id,
        this.telefono_institucion = this.telefono_institucion,
        this.tipo_docente = this.tipo_docente,
        this.titular_id = this.titular_id
        this.id = this.id
       
    }    
  }
  

