# Generated by Django 3.1.7 on 2021-04-24 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('idAministrador', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'administrador',
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('idDocente', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'docente',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionCv_Personalizado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bloque', models.CharField(max_length=150)),
                ('atributo', models.CharField(max_length=100)),
                ('visible_cv_resumido', models.BooleanField(default=True)),
                ('mapeo', models.CharField(max_length=150)),
                ('idDocente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Docente', to='cv_api.docente')),
            ],
            options={
                'db_table': 'configuracioncvPersonalizado',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionCv',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bloque', models.CharField(max_length=150)),
                ('atributo', models.CharField(max_length=100)),
                ('orden', models.IntegerField()),
                ('visible_cv_resumido', models.BooleanField(default=True)),
                ('visible_cv_completo', models.BooleanField(default=True)),
                ('mapeo', models.CharField(max_length=150)),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Administrador', to='cv_api.administrador')),
            ],
            options={
                'db_table': 'configuracionCV',
            },
        ),
    ]
