# Generated by Django 3.1.7 on 2021-11-28 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracioncv',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='configuracioncv_personalizado',
            name='cedula',
            field=models.CharField(max_length=11),
        ),
    ]
