# Generated by Django 3.1.7 on 2021-09-16 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracioncv_personalizado',
            name='cv',
            field=models.CharField(max_length=20),
        ),
    ]
