# Generated by Django 3.1.7 on 2021-10-05 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracioncv_personalizado',
            name='ordenCompleto',
        ),
        migrations.RemoveField(
            model_name='configuracioncv_personalizado',
            name='ordenResumido',
        ),
    ]
