# Generated by Django 3.1.7 on 2021-04-24 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuracioncv_personalizado',
            old_name='visible_cv_resumido',
            new_name='visible_cv_personalizado',
        ),
    ]
