# Generated by Django 3.1.7 on 2021-09-21 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioncv_personalizado',
            name='id_atributo',
            field=models.IntegerField(default=1),
        ),
    ]
