# Generated by Django 3.1.7 on 2022-02-24 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracioncv_personalizado',
            name='nombreBloque',
        ),
        migrations.AddField(
            model_name='bloque',
            name='nombreService',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='configuracioncv',
            name='bloqueService',
            field=models.CharField(default='articulos', max_length=150),
        ),
    ]
