# Generated by Django 3.1.7 on 2021-09-21 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv_api', '0002_configuracioncv_personalizado_id_atributo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracioncv_personalizado',
            name='id_atributo',
        ),
    ]
