# Generated by Django 3.1.7 on 2021-04-24 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_api', '0002_auto_20210424_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioncv_personalizado',
            name='cv',
            field=models.IntegerField(default=None),
        ),
    ]
