# Generated by Django 3.1.7 on 2021-12-16 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_api', '0002_auto_20211128_2357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreBloque', models.CharField(max_length=150)),
                ('url', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'servicio',
            },
        ),
    ]
