# Generated by Django 3.1.7 on 2021-09-29 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_api', '0003_remove_configuracioncv_personalizado_nombrebloque'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioncv_personalizado',
            name='nombreBloque',
            field=models.CharField(default='Articulos', max_length=20),
        ),
    ]
