# Generated by Django 3.1.7 on 2022-01-13 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_api', '0003_servicio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='nombreBloque',
            new_name='bloqueNombre',
        ),
        migrations.AlterField(
            model_name='servicio',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='url',
            field=models.URLField(max_length=300),
        ),
        migrations.AlterUniqueTogether(
            name='servicio',
            unique_together={('bloqueNombre', 'url')},
        ),
    ]
