# Generated by Django 3.1.7 on 2021-10-05 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_api', '0003_auto_20211005_0100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuracioncv_personalizado',
            old_name='ordenCompleto',
            new_name='orden',
        ),
        migrations.RemoveField(
            model_name='configuracioncv',
            name='orden',
        ),
        migrations.RemoveField(
            model_name='configuracioncv_personalizado',
            name='ordenResumido',
        ),
        migrations.AddField(
            model_name='configuracioncv',
            name='ordenCompleto',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='configuracioncv',
            name='ordenResumido',
            field=models.IntegerField(default=1),
        ),
    ]
