# Generated by Django 3.1.7 on 2021-04-24 22:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cv_api', '0003_configuracioncv_personalizado_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioncv_personalizado',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='configuracioncv_personalizado',
            name='nombre_cv',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
