# Generated by Django 3.1.7 on 2021-09-21 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_api', '0003_remove_configuracioncv_personalizado_id_atributo'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioncv_personalizado',
            name='id_atributo',
            field=models.IntegerField(default=1),
        ),
    ]
