# Generated by Django 3.1.7 on 2021-10-07 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_api', '0004_auto_20211005_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracioncv_personalizado',
            name='cedula',
            field=models.TextField(max_length=11),
        ),
    ]
