# Generated by Django 3.1.7 on 2021-10-26 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_api', '0005_auto_20211007_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracioncv_personalizado',
            name='fecha_registro',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='configuracioncv_personalizado',
            name='mapeo',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterUniqueTogether(
            name='configuracioncv_personalizado',
            unique_together={('bloque', 'atributo', 'nombre_cv', 'cedula')},
        ),
    ]
