# Generated by Django 3.1.7 on 2021-05-11 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_api', '0005_bloque'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloque',
            name='orden',
            field=models.IntegerField(default=1),
        ),
    ]
