# Generated by Django 3.1.7 on 2021-05-14 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_api', '0006_bloque_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioncv_personalizado',
            name='orden',
            field=models.IntegerField(default=1),
        ),
    ]
