# Generated by Django 3.1.7 on 2021-05-18 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_api', '0007_configuracioncv_personalizado_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioncv_personalizado',
            name='cedula',
            field=models.TextField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='configuracioncv_personalizado',
            name='cv',
            field=models.CharField(max_length=11),
        ),
    ]
