# Generated by Django 3.1.7 on 2021-05-20 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_api', '0008_auto_20210518_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioncv_personalizado',
            name='idSeleccionado',
            field=models.IntegerField(default=1, max_length=1000000),
            preserve_default=False,
        ),
    ]
