# Generated by Django 3.1.7 on 2021-11-24 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv_api', '0008_auto_20211124_0157'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='configuracioncv_personalizado',
            unique_together={('bloque', 'atributo', 'nombre_cv', 'cedula')},
        ),
    ]
