# Generated by Django 3.1.7 on 2021-05-20 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv_api', '0009_configuracioncv_personalizado_idseleccionado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuracioncv_personalizado',
            old_name='idSeleccionado',
            new_name='configuracionId',
        ),
    ]
