# Generated by Django 3.1.7 on 2021-05-22 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_api', '0010_auto_20210520_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracioncv_personalizado',
            name='configuracionId',
            field=models.IntegerField(),
        ),
    ]
