# Generated by Django 3.1.7 on 2021-05-22 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_api', '0011_auto_20210522_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='first_name',
            field=models.CharField(default='testname', max_length=100),
        ),
        migrations.AddField(
            model_name='docente',
            name='last_name',
            field=models.CharField(default='test_lastname', max_length=100),
        ),
        migrations.AddField(
            model_name='docente',
            name='username',
            field=models.CharField(default='username', max_length=100, unique=True),
        ),
    ]
