# Generated by Django 3.1.7 on 2021-05-23 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv_api', '0013_auto_20210523_0034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docente',
            old_name='idDocente',
            new_name='id_user',
        ),
    ]
