# Generated by Django 3.1.7 on 2021-05-23 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_api', '0014_auto_20210523_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloque',
            name='ordenPersonalizable',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bloque',
            name='ordenResumido',
            field=models.IntegerField(default=0),
        ),
    ]
