# Generated by Django 3.1.7 on 2021-05-24 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv_api', '0015_auto_20210523_0346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuracioncv_personalizado',
            old_name='idDocente',
            new_name='id_user',
        ),
    ]
