# Generated by Django 3.1.7 on 2021-09-02 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_api', '0019_auto_20210902_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloque',
            name='visible_cv_bloque',
            field=models.BooleanField(default=True),
        ),
    ]
